[website]
# 网站标题
title = "GalaxyPark"
# 副标题
subtitle = "subtitle"
# 网站描述
description = "Hey, I am Clover You, welcome here!"
# 网站关键字
keywords = ["LinYao", "林耀", "GalaxyPark", "银河公园", "摄影", "photography", "艺术", "art", "博客", "Blog", "Software Development", "C#", ".NET"]
# 博客作者名称
author = "LinYao"
# 部署后网站地址
domain = "https://www.ctong.top"
# 左上角 logo 图片
logo = "/logo@185×185.webp"
# 左上角 logo 文字
logoText = "GalaxyPark"
# 底部版权文案信息
copyright = "CC BY-NC-SA 4.0 2024-PRESENT © LinYao"

[theme]
# 默认主题模式
# mode = "light"
mode = "dark"

[navbar]
items = [
  { url = "/about", label = "About" },
  { url = "/", label = "Blog" },
  { url = "https://github.com/10hz-404", iconClass = "icon-[mdi--github]", target = "_blank" },
]
